Repository adobe/spacecat-shared, pull requests merged in 2024-06, with the labels that each got.

#254 feat: Add update queries for import-job and import-url entites
  packages/spacecat-shared-data-access/src/index.d.ts
  packages/spacecat-shared-data-access/src/service/import-job/accessPatterns.js
  packages/spacecat-shared-data-access/src/service/import-job/index.js
  packages/spacecat-shared-data-access/src/service/import-url/accessPatterns.js
  packages/spacecat-shared-data-access/src/service/import-url/index.js
  packages/spacecat-shared-data-access/test/unit/service/import-job/index.test.js
  packages/spacecat-shared-data-access/test/unit/service/import-url/index.test.js
  packages/spacecat-shared-data-access/test/unit/service/index.test.js
Labels: enhancement

#261 fix: Add an ExpressionAttributeName to fix issues with reserved keywords
  packages/spacecat-shared-data-access/src/service/import-job/accessPatterns.js
Labels: bug

#262 feat: query for URLs for a given jobID matching status
  packages/spacecat-shared-data-access/src/index.d.ts
  packages/spacecat-shared-data-access/src/index.js
  packages/spacecat-shared-data-access/src/service/import-url/accessPatterns.js
  packages/spacecat-shared-data-access/src/service/import-url/index.js
  packages/spacecat-shared-data-access/test/unit/service/import-url/index.test.js
  packages/spacecat-shared-data-access/test/unit/service/index.test.js
Labels: enhancement

#263 feat: opt-out broken-backlinks
  packages/spacecat-shared-data-access/src/models/site/audit-config-type.js
  packages/spacecat-shared-data-access/src/models/site/config.js
  packages/spacecat-shared-data-access/test/unit/models/site/audit-config-type.test.js
Labels: enhancement

#267 fix: some more tests
  packages/spacecat-shared-utils/test/helpers.test.js
Labels: test

#269 fix: #268 Import URL entities need a REDIRECT status, and additional properties for reporting
  package-lock.json
  packages/spacecat-shared-data-access/src/dto/import-url.js
  packages/spacecat-shared-data-access/src/models/importer/import-url.js
  packages/spacecat-shared-data-access/test/unit/models/importer/import-url.test.js
  packages/spacecat-shared-data-access/test/unit/service/import-url/index.test.js
Labels: enhancement

#257 feat: introduce organic keywords for ahrefs client and top keyword in top pages
  packages/spacecat-shared-ahrefs-client/src/index.d.ts
  packages/spacecat-shared-ahrefs-client/src/index.js
  packages/spacecat-shared-ahrefs-client/test/index.test.js
  packages/spacecat-shared-data-access/src/dto/site-top-page.js
  packages/spacecat-shared-data-access/src/index.d.ts
  packages/spacecat-shared-data-access/src/models/site-top-page.js
  packages/spacecat-shared-data-access/test/it/db.test.js
  packages/spacecat-shared-data-access/test/it/generateSampleData.js
  packages/spacecat-shared-data-access/test/unit/models/site-top-page.test.js
  packages/spacecat-shared-data-access/test/unit/service/site-top-pages/index.test.js
Labels: enhancement

#270 feat: overwrite broken-backlinks
  packages/spacecat-shared-data-access/src/models/site/audit-config-type.js
  packages/spacecat-shared-data-access/src/models/site/config.js
  packages/spacecat-shared-data-access/test/unit/models/site/audit-config-type.test.js
Labels: enhancement

#275 fix: sqs adapter records access
  packages/spacecat-shared-rum-api-client/test/index.test.js
  packages/spacecat-shared-utils/src/sqs.js
Labels: bug

#277 feat: add helix config to site/candidates
  packages/spacecat-shared-data-access/docs/schema.json
  packages/spacecat-shared-data-access/src/dto/site-candidate.js
  packages/spacecat-shared-data-access/src/dto/site.js
  packages/spacecat-shared-data-access/src/models/site-candidate.js
  packages/spacecat-shared-data-access/src/models/site.js
  packages/spacecat-shared-data-access/test/it/db.test.js
  packages/spacecat-shared-data-access/test/it/generateSampleData.js
  packages/spacecat-shared-data-access/test/unit/models/site-candidate.test.js
  packages/spacecat-shared-data-access/test/unit/models/site.test.js
  packages/spacecat-shared-rum-api-client/test/index.test.js
Labels: enhancement
