Repository adobe/spacecat-shared, pull requests merged in 2025-06, with the labels that each got.

#792 fix: type error when no roles in profile
  packages/spacecat-shared-ims-client/src/clients/ims-client.js
Labels: bug

#810 fix: sanitize headers before logging
  packages/spacecat-shared-gpt-client/src/clients/firefall-client.js
  packages/spacecat-shared-gpt-client/src/clients/genvar-client.js
  packages/spacecat-shared-gpt-client/src/utils.js
Labels: bug, security

#827 feat: add CDN logs config
  packages/spacecat-shared-data-access/src/models/site/config.js
  packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
Labels: enhancement

#834 fix: make filter value array
  packages/spacecat-shared-data-access/src/models/site/config.js
  packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
Labels: enhancement
